
package form;

import connect.Connect;
import dao.CT_HDBanHang_Dao;
import dao.HoaDonBH_Dao;
import entity.CT_HDBanHang;
import entity.HDBanHang;
import entity.SanPham;
import entity.TaiKhoan;
import form.FromCTSPBC;

import static form.FromCTSPBC.dataModelBC;
import static form.FromCTSPBC.tableSPBC;
import gui.Main;
import static gui.Main.tkDN;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Hashtable;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;


public class FormTKSPBC extends javax.swing.JPanel  {

    /**
     * Creates new form FormTKSPBC
     */
    private DefaultTableModel dataModelHDBH;
    private CT_HDBanHang_Dao cthd_dao;

    private ArrayList<CT_HDBanHang> List;
    DecimalFormat df = new DecimalFormat("#,##0 VND");
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

    public FormTKSPBC() {

        try {
            Connect.getInstance().connect();
        } catch (SQLException e) {
            // TODO: handle exception
            e.printStackTrace();
        }

        initComponents();
        table.fixTable(jScrollPane);
//        table.addMouseListener((MouseListener) this);
        cthd_dao = new CT_HDBanHang_Dao();
        updateTable();
    }

    private void updateTable() {
        List = cthd_dao.getAllCTHD();
        dataModelHDBH = (DefaultTableModel) table.getModel();
        for (CT_HDBanHang hdbh : List) {
            dataModelHDBH.addRow(new Object[]{hdbh.getSanPham().getMaSP(), hdbh.getSanPham().getTenSP(), hdbh.getSoLuong()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnTim = new swing.Button();
        jLabel15 = new javax.swing.JLabel();
        cbbThangSP = new swing.Combobox();
        cbbNgaySP = new swing.Combobox();
        jLabel12 = new javax.swing.JLabel();
        cbbNamSP = new swing.Combobox();
        RbtnNgaySP = new javax.swing.JRadioButton();
        RbtnThangSP = new javax.swing.JRadioButton();
        RbtnNamSP = new javax.swing.JRadioButton();
        btnCT = new swing.Button();
        btnIn = new swing.Button();
        jScrollPane = new javax.swing.JScrollPane();
        table = new swing.Table();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TOP 5 QUẦN ÁO BÁN CHẠY");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), null), "Thống Kê", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Tháng:");

        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/loupe.png"))); // NOI18N
        btnTim.setText("Thống Kê");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Ngày:");

        cbbThangSP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tất Cả", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cbbThangSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbThangSPActionPerformed(evt);
            }
        });

        cbbNgaySP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tất cả", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));
        cbbNgaySP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbNgaySPActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Năm:");

        cbbNamSP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tất Cả", "2021", "2022" }));

        RbtnNgaySP.setText("Thống Kê Theo Ngày");

        RbtnThangSP.setText("Thống Kê Theo Tháng");

        RbtnNamSP.setText("Thống Kê Theo Năm");

        btnCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/file.png"))); // NOI18N
        btnCT.setText("Xem Chi Tiết");
        btnCT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCTActionPerformed(evt);
            }
        });

        btnIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/file.png"))); // NOI18N
        btnIn.setText("In Báo Cáo");
        btnIn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(cbbNgaySP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RbtnNgaySP))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(cbbThangSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RbtnThangSP))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbbNamSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RbtnNamSP))
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCT, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIn, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(301, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbNgaySP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbThangSP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbNamSP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RbtnNgaySP)
                        .addComponent(RbtnThangSP)
                        .addComponent(RbtnNamSP))
                    .addComponent(btnCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Quần Áo", "Tên Quần Áo", "Số Lượng Bán "
            }
        ));
        table.setShowGrid(true);
        table.setShowVerticalLines(false);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane.setViewportView(table);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("THỐNG KÊ TOP 5 QUẦN ÁO BÁN CHẠY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1262, Short.MAX_VALUE)
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1323, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1262, Short.MAX_VALUE)
                    .addGap(51, 51, 51)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(798, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed

        String ngay = cbbNgaySP.getSelectedItem().toString().trim().equalsIgnoreCase("Tất Cả") ? "" : cbbNgaySP.getSelectedItem().toString().trim();
        String thang = cbbThangSP.getSelectedItem().toString().trim().equalsIgnoreCase("Tất Cả") ? "" : cbbThangSP.getSelectedItem().toString().trim();
        String nam = cbbNamSP.getSelectedItem().toString().trim().equalsIgnoreCase("Tất Cả") ? "" : cbbNamSP.getSelectedItem().toString().trim();
        if (RbtnNgaySP.isSelected()) {
            if (BatLoiNgay()) {
                xoaModel(table);
                ArrayList<CT_HDBanHang> Lis = new ArrayList<CT_HDBanHang>();
                Lis = cthd_dao.getNgay(ngay, thang, nam);
                if (Lis.size() > 0) {

                    for (CT_HDBanHang hdbh : Lis) {
                        dataModelHDBH.addRow(new Object[]{hdbh.getSanPham().getMaSP(), hdbh.getSanPham().getTenSP(), hdbh.getSoLuong()});
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Không Có Dữ Liệu Phù Hợp");
                    xoaModel(table);
                    updateTable();
                }
            }
        } else if (RbtnThangSP.isSelected()) {
            if (BatLoiThang()) {
                xoaModel(table);
                ArrayList<CT_HDBanHang> Lis = new ArrayList<CT_HDBanHang>();
                Lis = cthd_dao.getThang(thang, nam);
                if (Lis.size() > 0) {

                    for (CT_HDBanHang hdbh : Lis) {
                        dataModelHDBH.addRow(new Object[]{hdbh.getSanPham().getMaSP(), hdbh.getSanPham().getTenSP(), hdbh.getSoLuong()});
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Không Có Dữ Liệu Phù Hợp");
                    xoaModel(table);
                    updateTable();
                }
            }
        } else if (RbtnNamSP.isSelected()) {
            if (BatLoiNam()) {
                xoaModel(table);
                ArrayList<CT_HDBanHang> Lis = new ArrayList<CT_HDBanHang>();
                Lis = cthd_dao.getNam(nam);
                if (Lis.size() > 0) {

                    for (CT_HDBanHang hdbh : Lis) {
                        dataModelHDBH.addRow(new Object[]{hdbh.getSanPham().getMaSP(), hdbh.getSanPham().getTenSP(), hdbh.getSoLuong()});
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Không Có Dữ Liệu Phù Hợp");
                    xoaModel(table);
                    updateTable();
                }
            }
        }
    }//GEN-LAST:event_btnTimActionPerformed
    public void xoaModel(JTable table) {
        DefaultTableModel del = (DefaultTableModel) table.getModel();
        del.getDataVector().removeAllElements();
    }
    private void cbbNgaySPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbNgaySPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbNgaySPActionPerformed

    private void btnCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCTActionPerformed
        String ngay = cbbNgaySP.getSelectedItem().toString().trim().equalsIgnoreCase("Tất Cả") ? "" : cbbNgaySP.getSelectedItem().toString().trim();
        String thang = cbbThangSP.getSelectedItem().toString().trim().equalsIgnoreCase("Tất Cả") ? "" : cbbThangSP.getSelectedItem().toString().trim();
        String nam = cbbNamSP.getSelectedItem().toString().trim().equalsIgnoreCase("Tất Cả") ? "" : cbbNamSP.getSelectedItem().toString().trim();

        int r = table.getSelectedRow();
        if (r != -1) {
            new FromCTSPBC().setVisible(true);
            String masp = (String) table.getValueAt(r, 0);
             FromCTSPBC.maSP=masp;
            if (RbtnNgaySP.isSelected()) {
                if (BatLoiNgay()) {
                    dataModelBC = (DefaultTableModel) tableSPBC.getModel();
                    xoaModel(tableSPBC);
                    ArrayList<CT_HDBanHang> Lis = new ArrayList<CT_HDBanHang>();
                    Lis = cthd_dao.getCTSPNgay(masp, ngay, thang, nam);
                    if (Lis.size() > 0) {

                        for (CT_HDBanHang hdbh : Lis) {
                            dataModelBC.addRow(new Object[]{hdbh.getSanPham().getTenSP(), hdbh.getHoaDonBH().getMaHDBH(), hdbh.getSoLuong(), df.format(hdbh.getThanhTien())});
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Không Có Dữ Liệu Phù Hợp");
                        xoaModel(tableSPBC);

                    }
                }
            } else if (RbtnThangSP.isSelected()) {
                if (BatLoiThang()) {
                    dataModelBC = (DefaultTableModel) tableSPBC.getModel();
                    xoaModel(tableSPBC);
                    ArrayList<CT_HDBanHang> Lis = new ArrayList<CT_HDBanHang>();
                    Lis = cthd_dao.getCTSPThang(masp, thang, nam);
                    if (Lis.size() > 0) {

                        for (CT_HDBanHang hdbh : Lis) {
                            dataModelBC.addRow(new Object[]{hdbh.getSanPham().getTenSP(), hdbh.getHoaDonBH().getMaHDBH(), hdbh.getSoLuong(), df.format(hdbh.getThanhTien())});
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Không Có Dữ Liệu Phù Hợp");
                        xoaModel(tableSPBC);

                    }
                }
            } else if (RbtnNamSP.isSelected()) {
                if (BatLoiNam()) {
                    dataModelBC = (DefaultTableModel) tableSPBC.getModel();
                    xoaModel(tableSPBC);
                    ArrayList<CT_HDBanHang> Lis = new ArrayList<CT_HDBanHang>();
                    Lis = cthd_dao.getCTSPNam(masp, nam);
                    if (Lis.size() > 0) {
                        for (CT_HDBanHang hdbh : Lis) {
                            dataModelBC.addRow(new Object[]{hdbh.getSanPham().getTenSP(), hdbh.getHoaDonBH().getMaHDBH(), hdbh.getSoLuong(), df.format(hdbh.getThanhTien())});
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Không Có Dữ Liệu Phù Hợp");
                        xoaModel(tableSPBC);
                    }
                }
            }
        } else
            JOptionPane.showMessageDialog(null, "Chưa Chọn Quần Áo Để Xem Chi Tiết");
    }//GEN-LAST:event_btnCTActionPerformed

    public void printBillNam(String data,TaiKhoan tk, String source) {
        try {
            Connect.getInstance();
            Connection con = Connect.getConnection();
            Hashtable map = new Hashtable();
            JasperReport report = JasperCompileManager.compileReport(source);
            map.put("txtNam", data);
            map.put("ma", tk.getNhanVien().getMaNV().toString());
            map.put("ten", tk.getNhanVien().getTenNV().toString());
            map.put("cv", tk.getNhanVien().getChucVu().getTenCV().toString());
            JasperPrint p = JasperFillManager.fillReport(report, map, con);
            JasperViewer.viewReport(p, false);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }

    public void printBillThang(String data, String data1,TaiKhoan tk, String source) {
        try {
            Connect.getInstance();
            Connection con = Connect.getConnection();
            Hashtable map = new Hashtable();
            JasperReport report;
            report = JasperCompileManager.compileReport(source);
            map.put("txtThang", data);
            map.put("txtNam", data1);
            map.put("ma", tk.getNhanVien().getMaNV().toString());
            map.put("ten", tk.getNhanVien().getTenNV().toString());
            map.put("cv", tk.getNhanVien().getChucVu().getTenCV().toString());
            JasperPrint p = JasperFillManager.fillReport(report, map, con);
            JasperViewer.viewReport(p, false);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }

    public void printBillNgay(String data, String data1, String data2,TaiKhoan tk, String source) {
        try {
            Connect.getInstance();
            Connection con = Connect.getConnection();
            Hashtable map = new Hashtable();
            JasperReport report;
            report = JasperCompileManager.compileReport(source);
            map.put("txtNgay", data);
            map.put("txtThang", data1);
            map.put("txtNam", data2);
            map.put("ma", tk.getNhanVien().getMaNV().toString());
            map.put("ten", tk.getNhanVien().getTenNV().toString());
            map.put("cv", tk.getNhanVien().getChucVu().getTenCV().toString());
            JasperPrint p = JasperFillManager.fillReport(report, map, con);
            JasperViewer.viewReport(p, false);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }
    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed
        String ngay = cbbNgaySP.getSelectedItem().toString().trim().equalsIgnoreCase("Tất Cả") ? "" : cbbNgaySP.getSelectedItem().toString().trim();
        String nam = cbbNamSP.getSelectedItem().toString().trim().equalsIgnoreCase("Tất Cả") ? "" : cbbNamSP.getSelectedItem().toString().trim();
        String thang = cbbThangSP.getSelectedItem().toString().trim().equalsIgnoreCase("Tất Cả") ? "" : cbbThangSP.getSelectedItem().toString().trim();

        if (RbtnNgaySP.isSelected()) {
            if (BatLoiNgay()) {
                printBillNgay(ngay, thang, nam, Main.tkDN, "src\\main\\java\\report\\reportQABCNgay.jrxml");
            }
        } else if (RbtnThangSP.isSelected()) {
            if (BatLoiThang()) {
                printBillThang(thang, nam, Main.tkDN, "src\\main\\java\\report\\reportQABCThang.jrxml");
            }
        } else if (RbtnNamSP.isSelected()) {
            if (BatLoiNam()) {
                printBillNam(nam, Main.tkDN, "src\\main\\java\\report\\reportQABCNam.jrxml");
            }
        }
    }//GEN-LAST:event_btnInActionPerformed

    private void cbbThangSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbThangSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbThangSPActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
//        int r = table.getSelectedRow();
//        if (r != -1) {
//            FromCTSPBC.maSP = table.getValueAt(r, 0).toString();
//            System.out.println(table.getValueAt(r, 0).toString());
//        }
    }//GEN-LAST:event_tableMouseClicked

    private boolean BatLoiNam() {
        String nam = cbbNamSP.getSelectedItem().toString().trim().equalsIgnoreCase("Tất Cả") ? "" : cbbNamSP.getSelectedItem().toString().trim();
        if (!(nam.length() > 0)) {
            JOptionPane.showMessageDialog(null, "Bạn Chưa Chọn Năm");
            return false;
        }
        return true;

    }

    private boolean BatLoiThang() {
        String thang = cbbThangSP.getSelectedItem().toString().trim().equalsIgnoreCase("Tất Cả") ? "" : cbbThangSP.getSelectedItem().toString().trim();
        String nam = cbbNamSP.getSelectedItem().toString().trim().equalsIgnoreCase("Tất Cả") ? "" : cbbNamSP.getSelectedItem().toString().trim();
        if (!(thang.length() > 0)) {
            JOptionPane.showMessageDialog(null, "Bạn Chưa Chọn Tháng");
            return false;
        }
        if (!(nam.length() > 0)) {
            JOptionPane.showMessageDialog(null, "Bạn Chưa Chọn Năm");
            return false;
        }

        return true;

    }

    public boolean BatLoiNgay() {
        String ngay = cbbNgaySP.getSelectedItem().toString().trim().equalsIgnoreCase("Tất Cả") ? "" : cbbNgaySP.getSelectedItem().toString().trim();
        String thang = cbbThangSP.getSelectedItem().toString().trim().equalsIgnoreCase("Tất Cả") ? "" : cbbThangSP.getSelectedItem().toString().trim();
        String nam = cbbNamSP.getSelectedItem().toString().trim().equalsIgnoreCase("Tất Cả") ? "" : cbbNamSP.getSelectedItem().toString().trim();
        if (!(ngay.length() > 0)) {
            JOptionPane.showMessageDialog(null, "Bạn Chưa Chọn Ngày");
            return false;
        }
        if (!(thang.length() > 0)) {
            JOptionPane.showMessageDialog(null, "Bạn Chưa Chọn Tháng");
            return false;
        }
        if (!(nam.length() > 0)) {
            JOptionPane.showMessageDialog(null, "Bạn Chưa Chọn Năm");
            return false;
        }

        return true;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JRadioButton RbtnNamSP;
    public static javax.swing.JRadioButton RbtnNgaySP;
    public static javax.swing.JRadioButton RbtnThangSP;
    private swing.Button btnCT;
    private swing.Button btnIn;
    private swing.Button btnTim;
    public static swing.Combobox cbbNamSP;
    public static swing.Combobox cbbNgaySP;
    public static swing.Combobox cbbThangSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane;
    private swing.Table table;
    // End of variables declaration//GEN-END:variables

   

    

}
